import {createZandaBot} from './assets/zanda-bot.js';
const config=await fetch('./form-config.json').then(r=>r.json());
const $=s=>document.querySelector(s); const key='zanda:book_therapy:brief:v1';let values={},step=0;
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved?.values){values=saved.values;$('#remember').checked=true}}catch{}
const tips=['Pokud nemáte aktuální téma, klidně nechte výběr na Žankovi. U cíle pomůže jedna priorita: například návštěva knihkupectví.','U reference napište hlavně proč se vám líbí. I obyčejné „tyhle titulky neruší obraz“ nám velmi pomůže.','Je v pořádku natáčet telefonem. Napište, co máte k dispozici; plán tomu přizpůsobíme.','Tady si můžete projít své odpovědi. Toto je zatím náhled: nic se neodesílá ani nefakturuje.'];
const bot=createZandaBot($('#bot'),{expression:'R02',label:'Zandabot — nápověda k formuláři',idle:!matchMedia('(prefers-reduced-motion: reduce)').matches,onClick:()=>{$('#helper').hidden=!$('#helper').hidden}});
$('#close-helper').onclick=()=>$('#helper').hidden=true;
document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#helper').hidden=true});
const chips={q1:['Téma nechám navrhnout Žanka.'],q2:['Noví zákazníci','Současní zákazníci','Milovníci knih a designu','Lidé hledající dárek'],q3:['Návštěva knihkupectví','Prohlédnutí knihy na e-shopu','Účast na akci','Poznání značky'],q4:['Instagram','Facebook','Web','Placená reklama'],q9:['Natočíme podle scénáře','Plánujeme akci','Necháme si poradit']};
function save(){if($('#remember').checked){try{localStorage.setItem(key,JSON.stringify({values,version:1}))}catch{$('#status').textContent='Uložení na zařízení není dostupné. Odpovědi zůstávají v otevřeném formuláři.'}}}
function el(tag,attrs={},text){let n=document.createElement(tag);for(let [k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n}
function updateValue(f,input){values[f.id]=input.value;save();input.closest('.field').classList.remove('error');input.removeAttribute('aria-invalid');input.closest('.field').querySelector('.error-message')?.remove()}
function render(scroll=false){$('#fields').replaceChildren();$('#steps').replaceChildren();$('#status').textContent='';$('#status').className='';$('#review').replaceChildren();$('#review').hidden=step!==3;
config.steps.forEach((label,i)=>{const b=el('button',{type:'button',class:'step '+(i===step?'active':i<step?'done':''),'aria-current':i===step?'step':'false'});b.append(el('b',{},String(i+1).padStart(2,'0')),el('span',{},label));b.onclick=()=>{if(i<=step){step=i;render(true)}else if(i===step+1&&validate()){step=i;render(true)}else{$('#status').textContent='Projděte prosím postupně předchozí kroky.'}};$('#steps').append(b)});
$('#step-label').textContent=`KROK ${String(step+1).padStart(2,'0')} / 04`;$('#bar').style.width=((step+1)*25)+'%';$('#helper-copy').textContent=tips[step];
$('#heading').replaceChildren(el('h2',{},config.steps[step]),el('p',{class:'lead'},['Co má video říct. A komu.','Ať je v každém detailu cítit vaše značka.','Dobrý plán začíná tím, co máme k dispozici.','Ještě poslední pohled, než se pustíme do tvorby.'][step]));
config.fields.filter(f=>f.step===step).forEach(f=>{const box=el('div',{class:'field'});if(f.number)box.append(el('span',{class:'number'},`OTÁZKA ${String(f.number).padStart(2,'0')}`));const label=el('label',{for:f.id},f.label);if(!f.required)label.append(el('span',{class:'optional'},'volitelné'));box.append(label,el('p',{class:'hint',id:f.id+'-hint'},f.help));let input=el(f.type==='email'?'input':'textarea',{id:f.id,name:f.id,'aria-describedby':f.id+'-hint',placeholder:f.type==='email'?'vas@email.cz':'Vaše odpověď…'});if(f.type==='email'){input.type='email';input.autocomplete='email'}if(f.required)input.required=true;input.value=values[f.id]||'';input.oninput=()=>updateValue(f,input);if(chips[f.id]){const row=el('div',{class:'chips'});chips[f.id].forEach(t=>{let b=el('button',{type:'button',class:'chip'},t);b.onclick=()=>{input.value=t;updateValue(f,input);input.focus()};row.append(b)});box.append(row)}box.append(input);$('#fields').append(box)});
if(step===3){let c=el('div',{class:'review-card'});c.append(el('h3',{},'Jeden příběh. Tři začátky.'),el('p',{},'Ke stejnému videu připravíme tři varianty úvodu. Pokud máte dostupné zkušební Reels, můžete vyzkoušet reakce lidí, kteří vás zatím nesledují, a pak vybranou variantu sdílet se všemi. Vyšší dosah není zaručený.'),el('p',{},'Po briefu si potvrdíme rozsah. Následuje faktura na 4 000 Kč, po úhradě návrh tématu a scénáře, vaše schválení a natáčení. Potom se pustíme do střihu.'));$('#review').append(c,el('h3',{},'Vaše odpovědi'));config.fields.filter(f=>f.step<3).forEach(f=>{let row=el('div',{class:'answer'});row.append(el('strong',{},f.label),el('p',{},values[f.id]||'Necháme k doplnění.'));let edit=el('button',{type:'button'},'Upravit odpověď');edit.onclick=()=>{step=f.step;render(true);$('#'+f.id).focus()};row.append(edit);$('#review').append(row)})}
$('#back').hidden=step===0;$('#next').textContent=step===3?'Dokončit náhled →':config.steps[step+1]+' →';if(scroll)window.scrollTo({top:innerWidth<760?document.querySelector('.workspace').offsetTop-15:0,behavior:'instant'})}
function validate(){let first;config.fields.filter(f=>f.step===step).forEach(f=>{let n=$('#'+f.id),bad=f.required&&!n.value.trim()||f.type==='email'&&n.value&&!n.validity.valid;if(bad){n.closest('.field').classList.add('error');n.setAttribute('aria-invalid','true');if(!n.closest('.field').querySelector('.error-message'))n.after(el('p',{class:'error-message'},f.type==='email'?'Doplňte platnou e-mailovou adresu.':'Napište odpověď, nebo „nechám si doporučit“.'));first??=n}});if(first){first.focus();bot.react('chyba');return false}return true}
$('#form').onsubmit=e=>{e.preventDefault();if(!validate())return;if(step<3){step++;render(true);bot.flash('R02',1200)}else{$('#status').className='preview-message';$('#status').textContent='Náhled je dokončený. Odpovědi nebyly odeslány. Přijímání do ZandaVisuals OS a potvrzovací e-mail připojí další fáze implementace.';$('#status').scrollIntoView({block:'center'});bot.react('hotovo')}};
$('#back').onclick=()=>{step--;render(true)};$('#remember').onchange=()=>{if($('#remember').checked)save();else try{localStorage.removeItem(key)}catch{}};$('#clear').onclick=()=>{if(!confirm('Smazat všechny rozepsané odpovědi na tomto zařízení?'))return;values={};try{localStorage.removeItem(key)}catch{}step=0;render(true)};render();
